### ISSUE TITLE
Feature: don't git ignore cargo lock file

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/repo-query#4]
### Type of feature

🍕 Feature

### Current behavior

Currently, the cargo lock file is being ignored:

https://github.com/open-sauced/repo-query/blob/c71091e9a41266445875e476f027099655252911/.gitignore#L6-L8

We'll want to commit this to source control since we'll be building an atomic service.

### Suggested solution

Remove the above lines from the `.gitignore`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by Anush008** [comment]
https://github.com/open-sauced/repo-query/commit/62216094fb6a595c0a4b79e6fa971c28fd64c7f2
